In [11]:
import pandas as pd
df = pd.read_parquet('data_news_merged.parquet')
len(df)

963170

In [2]:
df.columns

Index(['id', 'link', 'domain', 'category', 'title', 'description', 'keywords',
       'author', 'publication_date', 'year', 'content', 'created_time',
       'updated_time'],
      dtype='str')

In [ ]:
duplicate_id = df[df.duplicated(subset=["id"], keep=False)]

print("Số dòng duplicate theo id:", len(duplicate_id))
duplicate_id.sort_values("id")

Số dòng duplicate theo id: 116896

,id,link,domain,category,title,description,keywords,author,publication_date,year,content,created_time,updated_time
0,1539751,https://thanhnien.vn/uu-tien-che-do-voi-nguoi-...,https://thanhnien.vn,Thời sự,Ưu tiên chế độ với người nghỉ việc trong vòng ...,Bộ Nội vụ khuyến khích sắp xếp tổ chức bộ máy ...,"sắp xếp tổ chức bộ máy, Bộ Nội vụ, công chức v...",Thu Hằng,2024-12-31 14:24:00,2024.0,Tại tờ trình Chính phủ về dự thảo Nghị định về...,NaN,NaN
904722,1539751,https://thanhnien.vn/uu-tien-che-do-voi-nguoi-...,https://thanhnien.vn,Thời sự,Ưu tiên chế độ với người nghỉ việc trong vòng ...,Bộ Nội vụ khuyến khích sắp xếp tổ chức bộ máy ...,"sắp xếp tổ chức bộ máy, Bộ Nội vụ, công chức v...",Thu Hằng,2024-12-31 14:24:00,2024.0,Tại tờ trình Chính phủ về dự thảo Nghị định về...,NaN,NaN
1,1539752,https://thanhnien.vn/bat-giam-truong-phong-qua...,https://thanhnien.vn,Thời sự,Bắt giam Trưởng phòng Quản lý đô thị TP.Hội An,"Công an tỉnhQuảng Namvừa khởi tố, bắt tạm giam...","nhận hối lộ, đưa hối lộ, sử dụng tài liệu giả,...",Mạnh Cường,2024-12-31 12:08:00,2024.0,"Sáng 31.12, Cơ quan CSĐT Công an tỉnhQuảng Nam...",NaN,NaN
904723,1539752,https://thanhnien.vn/bat-giam-truong-phong-qua...,https://thanhnien.vn,Thời sự,Bắt giam Trưởng phòng Quản lý đô thị TP.Hội An,"Công an tỉnhQuảng Namvừa khởi tố, bắt tạm giam...","nhận hối lộ, đưa hối lộ, sử dụng tài liệu giả,...",Mạnh Cường,2024-12-31 12:08:00,2024.0,"Sáng 31.12, Cơ quan CSĐT Công an tỉnhQuảng Nam...",NaN,NaN
2,1539753,https://thanhnien.vn/ung-cuu-5-thuyen-vien-tru...,https://thanhnien.vn,Thời sự,Ứng cứu 5 thuyền viên Trung Quốc trôi dạt trên...,5 thuyền viên Trung Quốc bị tai nạn trên biển....,"Thuyền viên, Cảnh Sát Biển, Thuyền trưởng, tàu cá",Bắc Bình,2024-12-31 11:57:00,2024.0,"Ngày 31.12, tin từ Bộ Tư lệnh Vùngcảnh sát bi...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58445,1598302,https://thanhtra.com.vn/tai-chinh-701717FFD/vi...,https://thanhtra.com.vn,/tai-chinh-701717FFD,"Vi phạm trong lĩnh vực chứng khoán, Hoàng Anh ...",(Thanh tra) - Ủy ban Chứng khoán Nhà nước đã b...,"{""Ủy ban Chứng khoán Nhà nước"": ""https://thanh...",NaN,2022-08-18 17:00:00.0,2022.0,"Vi phạm trong lĩnh vực chứng khoán, Hoàng Anh ...",NaN,NaN
963168,1598303,https://thanhtra.com.vn/tai-chinh-701717FFD/cu...,https://thanhtra.com.vn,/tai-chinh-701717FFD,Cục Thuế Hòa Bình tuyên dương 32 người nộp thuế,"(Thanh tra)- Theo lãnh đạo Cục Thuế Hòa Bình, ...","{""Hòa Bình"": ""https://thanhtra.com.vn/tag/hoa-...",Uyên Uyên,2022-08-16 06:35:00.0,2022.0,Cục Thuế Hòa Bình tuyên dương 32 người nộp thu...,NaN,NaN
58446,1598303,https://thanhtra.com.vn/tai-chinh-701717FFD/cu...,https://thanhtra.com.vn,/tai-chinh-701717FFD,Cục Thuế Hòa Bình tuyên dương 32 người nộp thuế,"(Thanh tra)- Theo lãnh đạo Cục Thuế Hòa Bình, ...","{""Hòa Bình"": ""https://thanhtra.com.vn/tag/hoa-...",Uyên Uyên,2022-08-16 06:35:00.0,2022.0,Cục Thuế Hòa Bình tuyên dương 32 người nộp thu...,NaN,NaN
58447,1598304,https://thanhtra.com.vn/an-sinh-AFA9C5670/tri-...,https://thanhtra.com.vn,/an-sinh-AFA9C5670,Trí tuệ nhân tạo có thay thế được phóng viên?,"(Thanh tra) - Ngày nay, với sự phát triển khôn...","{""lao động"": ""https://thanhtra.com.vn/tag/lao-...",NaN,2021-06-22 13:32:00.0,2021.0,Trí tuệ nhân tạo có thay thế được phóng viên?B...,NaN,NaN
963169,1598304,https://thanhtra.com.vn/an-sinh-AFA9C5670/tri-...,https://thanhtra.com.vn,/an-sinh-AFA9C5670,Trí tuệ nhân tạo có thay thế được phóng viên?,"(Thanh tra) - Ngày nay, với sự phát triển khôn...","{""lao động"": ""https://thanhtra.com.vn/tag/lao-...",NaN,2021-06-22 13:32:00.0,2021.0,Trí tuệ nhân tạo có thay thế được phóng viên?B...,NaN,NaN

In [4]:
df.head(5)

,id,link,domain,category,title,description,keywords,author,publication_date,year,content,created_time,updated_time
0,1539751,https://thanhnien.vn/uu-tien-che-do-voi-nguoi-...,https://thanhnien.vn,Thời sự,Ưu tiên chế độ với người nghỉ việc trong vòng ...,Bộ Nội vụ khuyến khích sắp xếp tổ chức bộ máy ...,"sắp xếp tổ chức bộ máy, Bộ Nội vụ, công chức v...",Thu Hằng,2024-12-31 14:24:00,2024.0,Tại tờ trình Chính phủ về dự thảo Nghị định về...,NaN,NaN
1,1539752,https://thanhnien.vn/bat-giam-truong-phong-qua...,https://thanhnien.vn,Thời sự,Bắt giam Trưởng phòng Quản lý đô thị TP.Hội An,"Công an tỉnhQuảng Namvừa khởi tố, bắt tạm giam...","nhận hối lộ, đưa hối lộ, sử dụng tài liệu giả,...",Mạnh Cường,2024-12-31 12:08:00,2024.0,"Sáng 31.12, Cơ quan CSĐT Công an tỉnhQuảng Nam...",NaN,NaN
2,1539753,https://thanhnien.vn/ung-cuu-5-thuyen-vien-tru...,https://thanhnien.vn,Thời sự,Ứng cứu 5 thuyền viên Trung Quốc trôi dạt trên...,5 thuyền viên Trung Quốc bị tai nạn trên biển....,"Thuyền viên, Cảnh Sát Biển, Thuyền trưởng, tàu cá",Bắc Bình,2024-12-31 11:57:00,2024.0,"Ngày 31.12, tin từ Bộ Tư lệnh Vùngcảnh sát bi...",NaN,NaN
3,1539754,https://thanhnien.vn/o-to-lao-xuong-song-2-ngu...,https://thanhnien.vn,Lao động - Việc làm,"Ô tô lao xuống sông, 2 người tử vong","Khi trục vớt chiếc xe ô tô bị rơi xuống sông, ...","Quốc lộ 15, Đội CSGT Công an H.Đức Thọ, Nạn Nh...",Phạm Đức,2024-12-31 10:52:00,2024.0,"Sáng 31.12, trao đổi với PVThanh Niên, một lãn...",NaN,NaN
4,1539762,https://thanhnien.vn/chat-luong-lao-dong-tphcm...,https://thanhnien.vn,Lao động - Việc làm,Chất lượng lao động TP.HCM mới đạt mức đáp ứng...,Doanh nghiệp đánh giá mức độ đáp ứng các tiêu ...,"lao động, người lao động, nhu cầu nhân lực, Nh...",Phạm Thu Ngân,2024-12-31 10:47:00,2024.0,"Chất lượnglao độngnằm ở mức ""đáp ứng"" và ""đáp ...",NaN,NaN

In [9]:
import pandas as pd

file_path = "data_news_merged.parquet"

file_path1 = "data_news_merged_1.parquet"

df = pd.read_parquet(file_path)

before = len(df)

df = df.drop_duplicates(
    subset=["id"],
    keep="first"
)

after = len(df)

df.to_parquet(
    file_path1,
    index=False,
    compression="zstd"
)

print(f"Trước khi xóa: {before:,} dòng")
print(f"Sau khi xóa: {after:,} dòng")
print(f"Đã xóa: {before - after:,} dòng duplicate")

Trước khi xóa: 963,170 dòng
Sau khi xóa: 904,722 dòng
Đã xóa: 58,448 dòng duplicate

In [10]:
duplicate_id = df[df.duplicated(subset=["id"], keep=False)]

print("Số dòng duplicate theo id:", len(duplicate_id))
# duplicate_id.sort_values("id")

Số dòng duplicate theo id: 0

In [14]:
import pandas as pd
df = pd.read_parquet('data_news_merged_good.parquet')
len(df)

904722

In [15]:
df.head(20).to_csv("data_news_merged_sample.csv", index=False, encoding="utf-8-sig")